---
version: 1.0
gsf:
  basic:
    model_encoder_type: rgcn
    graph_name: ogbn-mag
    backend: gloo
    ip_config: /data/ip_list_p1_metal.txt
    part_config: /data/ogbn-mag-lp-1p/ogbn-mag.json
    verbose: false
    eval_frequency: 1000
  gnn:
    fanout: "20,15"
    num_layers: 2
    hidden_size: 128
    use_mini_batch_infer: false
  input:
    restore_model_path: null
  output:
    save_model_path: /data/ogbn-map-lp/model/
    save_embeds_path: /data/ogbn-map-lp/embed/
    save_model_frequency: 1000
  hyperparam:
    dropout: 0.
    lr: 0.0005
    num_epochs: 2
    batch_size: 4096
    wd_l2norm: 0
  rgcn:
    num_bases: -1
    use_self_loop: true
    lp_decoder_type: dot_product
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  link_prediction:
    num_negative_edges: 4
    num_negative_edges_eval: 16
    train_negative_sampler: joint
    eval_etype:
      - "author,writes,paper"
    train_etype:
      - "author,writes,paper"
    exclude_training_targets: false
    reverse_edge_types_map: []
